"""Pydantic V2 models for OrchestratedRoutine."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class Movement(BaseModel):
    """A single movement / exercise within a routine protocol."""

    name: str = Field(..., description="Movement name, e.g. 'Cat-Cow Stretch'")
    duration_secs: int = Field(..., ge=10, description="Duration in seconds")
    description: str = Field(..., description="Guidance for performing the movement")
    body_area: str = Field(..., description="Primary body area targeted")


class GeneratedProtocol(BaseModel):
    """The full break-routine protocol generated by the agent."""

    title: str = Field(..., description="Human-readable routine title")
    duration_mins: int = Field(..., ge=1, description="Total routine duration in minutes")
    movements: List[Movement] = Field(..., min_length=1)


class OrchestratedRoutine(BaseModel):
    """A scheduled or completed routine stored in the `routines` collection."""

    user_id: str = Field(..., description="Owner user ID")
    scheduled_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    associated_calendar_event_id: Optional[str] = Field(
        default=None, description="ID of a linked Google Calendar event (if any)"
    )
    status: Literal["scheduled", "in_progress", "completed", "dismissed"] = Field(
        default="scheduled"
    )
    generated_protocol: GeneratedProtocol

    model_config = {"populate_by_name": True, "json_encoders": {datetime: lambda v: v.isoformat()}}
